
Usuarios = (

# ('nombre.apellido', 'OTRO', datetime(2001,01,02), Pais.objects.get(pais='México').id, 'RFCnombre.apellido', 'CURPnombre.apellido', 'direccion1', 'direccion2', Ciudad.objects.get(ciudad='Morelia').id, 'phone', 'cel', 'url', 'sni', 'PRIDE-', datetime(2001,01,02), datetime(2001,01,02)),

#tabla Autores
('hilda.rivas', 'Hilda', 'Rivas', tipo = 'TECNICO', none, pais_origen = Pais.objects.get(pais='Méxicohilda.rivas 'Hildahilda.rivas 'Hilda.Rivas', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('ana.burgos', 'Ana', 'Burgos', 'OTRO', none, Pais.objects.get(pais='México').id, 'ana.burgos', 'ana.burgos', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('manuel.mendoza', 'Manuel', 'Mendoza', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'manuel.mendoza', 'manuel.mendoza', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'D', none, none),
('maria.ramirez', 'María', 'Ramírez', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'maria.ramirez', 'maria.ramirez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'D', none, none),
('margaret.skutsch', 'Margaret', 'Skutsch', 'OTRO', none, Pais.objects.get(pais='México').id, 'margaret.skutsch', 'margaret.skutsch', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('jaime.paneque', 'Jaime', 'Paneque', 'INVESTIGADOR', none, Pais.objects.get(pais='España').id, 'jaime.paneque', 'jaime.paneque', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'B', none, none),
('yan.gao', 'Yan', 'Gao', 'TECNICO', none, Pais.objects.get(pais='China').id, 'yan.gao', 'yan.gao', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'B', none, none),
('claudio.garibay', 'Claudio', 'Garibay', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'claudio.garibay', 'claudio.garibay', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('gerardo.bocco', 'Gerardo', 'Bocco', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'gerardo.bocco', 'gerardo.bocco', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'D', none, none),
('antonio.vieyra', 'Antonio', 'Vieyra', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'antonio.vieyra', 'antonio.vieyra', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('yadira.mendez-lemus', 'Yadira', 'Méndez-Lemus', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'yadira.mendez-lemus', 'yadira.mendez-lemus', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'B', none, none),
('angel.priego', 'Angel', 'Priego', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'angel.priego', 'angel.priego', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('manuel.bollo', 'Manuel', 'Bollo', 'TECNICO', none, Pais.objects.get(pais='México').id, 'manuel.bollo', 'manuel.bollo', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'D', none, none),
('francisco.bautista', 'Francisco', 'Bautista', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'francisco.bautista', 'francisco.bautista', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('alejandra.larrazabal', 'Alejandra', 'Larrazábal', 'TECNICO', none, Pais.objects.get(pais='Bolivia').id, 'alejandra.larrazabal', 'alejandra.larrazabal', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('alejandro.velazquez', 'Alejandro', 'Velázquez', 'OTRO', none, Pais.objects.get(pais='México').id, 'alejandro.velazquez', 'alejandro.velazquez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('alejandro.velazques', 'Alejandro', 'Velázques', 'OTRO', none, Pais.objects.get(pais='México').id, 'alejandro.velazques', 'alejandro.velazques', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('gabriela.cuevas', 'Gabriela', 'Cuevas', 'TECNICO', none, Pais.objects.get(pais='México').id, 'gabriela.cuevas', 'gabriela.cuevas', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'B', none, none),
('angel.priego', 'Ángel', 'Priego', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'angel.priego', 'angel.priego', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('jean-francois.mas', 'Jean-Francois', 'Mas', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'jean-francois.mas', 'jean-francois.mas', '', '', Ciudad.objects.get(ciudad='Morelia').id '', '', '', '', 'D', none, none),
('frida.guiza', 'Frida', 'Güiza', 'OTRO', none, Pais.objects.get(pais='México').id, 'frida.guiza', 'frida.guiza', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('michael.mccall', 'Michael', 'McCall', 'INVESTIGADOR', none, Pais.objects.get(pais='Reino Unido').id, 'michael.mccall', 'michael.mccall', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'D', none, none),
('rosaura.paez', 'Rosaura', 'Páez', 'TECNICO', none, Pais.objects.get(pais='México').id, 'rosaura.paez', 'rosaura.paez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('adrian.ghilardi', 'Adrián', 'Ghilardi', 'INVESTIGADOR', none, Pais.objects.get(pais='Italia').id, 'adrian.ghilardi', 'adrian.ghilardi', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'B', none, none),
('jose.navarrete', 'José', 'Navarrete', 'TECNICO', none, Pais.objects.get(pais='México').id, 'jose.navarrete', 'jose.navarrete', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('pedro.urquijo', 'Pedro', 'Urquijo', 'TECNICO', none, Pais.objects.get(pais='México').id, 'pedro.urquijo', 'pedro.urquijo', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'D', none, none),
('marta.astier', 'Marta', 'Astier', 'OTRO', none, Pais.objects.get(pais='México').id, 'marta.astier', 'marta.astier', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('brian.napoletano', 'brian', 'napoletano', 'OTRO', none, Pais.objects.get(pais='México').id, 'brian.napoletano', 'brian.napoletano', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('lorena.poncela', 'Lorena', 'Poncela', 'OTRO', none, Pais.objects.get(pais='España').id, 'lorena.poncela', 'lorena.poncela', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('mariana.vallejo', 'Mariana', 'Vallejo', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'mariana.vallejo', 'mariana.vallejo', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('sara.barrasa', 'Sara', 'Barrasa', 'OTRO', none, Pais.objects.get(pais='España').id, 'sara.barrasa', 'sara.barrasa', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'B', none, none),
('arturo.muniz', 'Arturo', 'Muñiz', 'OTRO', none, Pais.objects.get(pais='México').id, 'arturo.muniz', 'arturo.muniz', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('hebe.vessuri', 'Hebe', 'Vessuri', 'OTRO', none, Pais.objects.get(pais='México').id, 'hebe.vessuri', 'hebe.vessuri', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('rosa.rivas', 'Rosa', 'Rivas', 'OTRO', none, Pais.objects.get(pais='México').id, 'rosa.rivas', 'rosa.rivas', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('manuel.zavala', 'Manuel', 'Zavala', 'OTRO', none, Pais.objects.get(pais='México').id, 'manuel.zavala', 'manuel.zavala', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('luis.morales', 'Luis', 'Morales', 'TECNICO', none, Pais.objects.get(pais='México').id, 'luis.morales', 'luis.morales', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'D', none, none),
('maria.gonzalez', 'Maria', 'González', 'INVESTIGADOR', none, Pais.objects.get(pais='España').id, 'maria.gonzalez', 'maria.gonzalez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('raquel.gonzalez', 'Raquel', 'González', 'TECNICO', none, Pais.objects.get(pais='México').id, 'raquel.gonzalez', 'raquel.gonzalez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('omar.montano', 'Omar', 'Montaño', 'OTRO', none, Pais.objects.get(pais='México').id, 'omar.montano', 'omar.montano', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('karine.lefebvre', 'karine', 'lefebvre', 'OTRO', none, Pais.objects.get(pais='Francia').id, 'karine.lefebvre', 'karine.lefebvre', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'PRIDE-', none, none),
('maria.carmona', 'María', 'Carmona', 'TECNICO', none, Pais.objects.get(pais='México').id, 'maria.carmona', 'maria.carmona', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('arturo.balderas', 'Arturo', 'Balderas', 'OTRO', none, Pais.objects.get(pais='México').id, 'arturo.balderas', 'arturo.balderas', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('frida.guiza', 'Frida', 'Guiza', 'OTRO', none, Pais.objects.get(pais='México').id, 'frida.guiza', 'frida.guiza', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('frida.larrazabal', 'Frida', 'Larrazabal', 'OTRO', none, Pais.objects.get(pais='México').id, 'frida.larrazabal', 'frida.larrazabal', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('alejandro.velazquez', 'Alejandro', 'Velazquez', 'OTRO', none, Pais.objects.get(pais='México').id, 'alejandro.velazquez', 'alejandro.velazquez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('adriana.flores', 'Adriana', 'Flores', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'adriana.flores', 'adriana.flores', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('armonia.borrego', 'Armonía', 'Borrego', 'OTRO', none, Pais.objects.get(pais='México').id, 'armonia.borrego', 'armonia.borrego', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('hernando.rodriguez', 'Hernando', 'Rodriguez', 'OTRO', none, Pais.objects.get(pais='México').id, 'hernando.rodriguez', 'hernando.rodriguez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('sara.ortiz', 'Sara', 'Ortiz', 'OTRO', none, Pais.objects.get(pais='México').id, 'sara.ortiz', 'sara.ortiz', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('roser.manejo', 'Roser', 'Manejo', 'OTRO', none, Pais.objects.get(pais='México').id, 'roser.manejo', 'roser.manejo', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('pablo.argueta', 'Pablo', 'Argueta', 'OTRO', none, Pais.objects.get(pais='México').id, 'pablo.argueta', 'pablo.argueta', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('jose.vieyra', 'José', 'Vieyra', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'jose.vieyra', 'jose.vieyra', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'C', none, none),
('yadira.mendez', 'Yadira', 'Mendez', 'INVESTIGADOR', none, Pais.objects.get(pais='México').id, 'yadira.mendez', 'yadira.mendez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', 'B', none, none),
('beatriz.tejera', 'Beatriz', 'Tejera', 'OTRO', none, Pais.objects.get(pais='México').id, 'beatriz.tejera', 'beatriz.tejera', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('ana.moreno', 'Ana', 'Moreno', 'OTRO', none, Pais.objects.get(pais='México').id, 'ana.moreno', 'ana.moreno', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('marcela.morales', 'Marcela', 'Morales', 'OTRO', none, Pais.objects.get(pais='México').id, 'marcela.morales', 'marcela.morales', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('jorge.gonzalez', 'Jorge', 'Gonzalez', 'OTRO', none, Pais.objects.get(pais='México').id, 'jorge.gonzalez', 'jorge.gonzalez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('dante.ayala', 'Dante', 'Ayala', 'OTRO', none, Pais.objects.get(pais='México').id, 'dante.ayala', 'dante.ayala', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('jose.pimentel', 'Jose', 'Pimentel', 'OTRO', none, Pais.objects.get(pais='México').id, 'jose.pimentel', 'jose.pimentel', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('martha.velazquez', 'Martha', 'Velazquez', 'OTRO', none, Pais.objects.get(pais='México').id, 'martha.velazquez', 'martha.velazquez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('rocio.aguirre', 'Rocío', 'Aguirre', 'OTRO', none, Pais.objects.get(pais='México').id, 'rocio.aguirre', 'rocio.aguirre', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('margarita.alvarado', 'Margarita', 'Alvarado', 'OTRO', none, Pais.objects.get(pais='México').id, 'margarita.alvarado', 'margarita.alvarado', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('saray.bucio', 'Saray', 'Bucio', 'OTRO', none, Pais.objects.get(pais='México').id, 'saray.bucio', 'saray.bucio', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('carina.grajales', 'Carina', 'Grajales', 'OTRO', none, Pais.objects.get(pais='México').id, 'carina.grajales', 'carina.grajales', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('alina.alvarez', 'Alina', 'Alvarez', 'OTRO', none, Pais.objects.get(pais='Argentina').id, 'alina.alvarez', 'alina.alvarez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),

#tabla pd_alumnos

('luis.garcia', 'Luis', 'García', 'OTRO', none, Pais.objects.get(pais='México').id, 'luis.garcia', 'luis.garcia', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('luz.garcia', 'Luz', 'García', 'OTRO', none, Pais.objects.get(pais='México').id, 'luz.garcia', 'luz.garcia', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('luis.ramirez', 'Luis', 'Ramírez', 'OTRO', none, Pais.objects.get(pais='México').id, 'luis.ramirez', 'luis.ramirez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('maria.vizcaino', 'María', 'Vizcaíno', 'OTRO', none, Pais.objects.get(pais='México').id, 'maria.vizcaino', 'maria.vizcaino', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('andrew.boni', 'Andrew', 'Boni', 'OTRO', none, Pais.objects.get(pais='México').id, 'andrew.boni', 'andrew.boni', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),

#tabla comitestuto

('john.healey', 'John', 'Healey', 'OTRO', none, Pais.objects.get(pais='México').id, 'john.healey', 'john.healey', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('eduardo.frapolli', 'Eduardo', 'Frapolli', 'OTRO', none, Pais.objects.get(pais='México').id, 'eduardo.frapolli', 'eduardo.frapolli', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('miguel.marti­nez', 'Miguel', 'Martí­nez', 'OTRO', none, Pais.objects.get(pais='México').id, 'miguel.marti­nez', 'miguel.marti­nez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('g.legorreta', 'G', 'Legorreta', 'OTRO', none, Pais.objects.get(pais='México').id, 'g.legorreta', 'g.legorreta', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('j.tiburio', 'J', 'Tiburio', 'OTRO', none, Pais.objects.get(pais='México').id, 'j.tiburio', 'j.tiburio', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('lucia.almeida', 'Lucia', 'Almeida', 'OTRO', none, Pais.objects.get(pais='México').id, 'lucia.almeida', 'lucia.almeida', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('roberto.lindig', 'Roberto', 'Lindig', 'OTRO', none, Pais.objects.get(pais='México').id, 'roberto.lindig', 'roberto.lindig', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('enrique.ojeda', 'Enrique', 'Ojeda', 'OTRO', none, Pais.objects.get(pais='México').id, 'enrique.ojeda', 'enrique.ojeda', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('jose.farina', 'José', 'Fariña', 'OTRO', none, Pais.objects.get(pais='México').id, 'jose.farina', 'jose.farina', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('jesus.fuentes', 'Jesús', 'Fuentes', 'OTRO', none, Pais.objects.get(pais='México').id, 'jesus.fuentes', 'jesus.fuentes', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('sophie.avila', 'Sophie', 'Avila', 'OTRO', none, Pais.objects.get(pais='México').id, 'sophie.avila', 'sophie.avila', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('guillermo.salas', 'Guillermo', 'Salas', 'OTRO', none, Pais.objects.get(pais='México').id, 'guillermo.salas', 'guillermo.salas', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('gian.delgado', 'Gian', 'Delgado', 'OTRO', none, Pais.objects.get(pais='México').id, 'gian.delgado', 'gian.delgado', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('octavio.gonzalez', 'Octavio', 'González', 'OTRO', none, Pais.objects.get(pais='México').id, 'octavio.gonzalez', 'octavio.gonzalez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('jose.hernandez', 'José', 'Hernández', 'OTRO', none, Pais.objects.get(pais='México').id, 'jose.hernandez', 'jose.hernandez', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('leticia.merino', 'Leticia', 'Merino', 'OTRO', none, Pais.objects.get(pais='México').id, 'leticia.merino', 'leticia.merino', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),
('luis.macias', 'Luis', 'Macías', 'OTRO', none, Pais.objects.get(pais='México').id, 'luis.macias', 'luis.macias', '', '', Ciudad.objects.get(ciudad='Morelia').id, '', '', '', '', '-', none, none),


)
